/**
 * Gemini Images Service (Imagen 3.0 Fast)
 * ---------------------------------------
 * Thin wrapper over Google AI Studio Images REST API.
 * Uses server-side key from env: GEMINI_API_KEY or NEXT_PUBLIC_GEMINI_API_KEY (fallback).
 */

export interface GenerateImageOptions {
  prompt: string;
  aspectRatio?: '1:1' | '16:9' | '9:16' | '4:3' | '3:4';
  
  // number of images to generate (1-4 typical)
  n?: number;
  // "high", "medium", "low" guidance scale equivalent (model specific)
  quality?: 'standard' | 'high' | 'draft';
  // safety options placeholder
  
}

export interface GeneratedImage {
  mimeType: string;
  data: string; // base64
}

export interface GenerateImageResponse {
  images: GeneratedImage[];
  model: string;
  prompt: string;
}

const DEFAULT_MODEL = 'imagen-3.0-generate-002';

function getApiKey(): string {
  const key = process.env.GEMINI_API_KEY || process.env.NEXT_PUBLIC_GEMINI_API_KEY;
  if (!key) {
    throw new Error('Missing GEMINI_API_KEY');
  }
  return key;
}

// Calls Imagen REST endpoint directly using Google AI Studio API
export async function generateImagesViaRest(options: GenerateImageOptions): Promise<GenerateImageResponse> {
  const apiKey = getApiKey();
  const model = DEFAULT_MODEL;

  console.log('🎨 Using Imagen model:', model);
  console.log('🎨 Generating image for prompt:', options.prompt.substring(0, 100));

  // Imagen 3.0 uses 'predict' method instead of 'generateImage'
  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:predict?key=${apiKey}`;

  const body: any = {
    instances: [{
      prompt: options.prompt,
    }],
    parameters: {
      // Aspect ratio support
      aspectRatio: options.aspectRatio || '1:1',
      // Number of images
      sampleCount: Math.min(Math.max(options.n ?? 1, 1), 4),
    }
  };

  console.log('📡 Calling Imagen API:', endpoint.replace(apiKey, '***'));

  const res = await fetch(endpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(body)
  });

  console.log('📡 Imagen API response status:', res.status);

  if (!res.ok) {
    const text = await res.text();
    console.error('❌ Imagen API error:', text);
    throw new Error(`Imagen API error ${res.status}: ${text}`);
  }

  const json = await res.json();
  console.log('📦 Imagen API response:', JSON.stringify(json).substring(0, 200));

  // Imagen 3.0 returns predictions with base64 data
  const predictions = json.predictions || [];
  const images = predictions.map((pred: any) => ({
    mimeType: pred.mimeType || 'image/png',
    data: pred.bytesBase64Encoded || pred.image || ''
  }));

  if (images.length === 0) {
    throw new Error('No images generated by Imagen API');
  }

  console.log('✅ Generated', images.length, 'image(s)');

  return {
    images,
    model,
    prompt: options.prompt
  };
}

export default {
  generateImagesViaRest
};
